org: stoerk
app: sillium-apis
service: awsbudget

frameworkVersion: '2'

package:
  individually: true

custom:
  stage: ${opt:stage}
  dev: 
    domainName: ${self:service}.dev.sillium.org
    logLevel: DEBUG
  prod:
    domainName: ${self:service}.sillium.org
    logLevel: INFO
  apiCloudFront:
    domain: ${self:custom.${self:custom.stage}.domainName}
    certificate: ${param:certificateArn}
    logging:
      bucket: sillium-apis-cloudfront-logs.s3.amazonaws.com
      prefix: ${self:service}/${self:custom.stage}
    cookies: none
  pythonRequirements:
    pythonBin: python3

plugins:
  - serverless-python-requirements
  - serverless-api-cloudfront
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}
  region: 'eu-central-1'
  logRetentionInDays: 7
  lambdaHashingVersion: 20201221
  deploymentBucket: sillium-apis-serverless-deployments
  stackTags:
    source: https://github.com/Sillium/awsbudget
    serverlessOrg: ${self:org}
    serverlessApp: ${self:app}
    serverlessService: ${self:service}
    serverlessStage: ${self:custom.stage}
  environment:
    LOG_LEVEL: ${self:custom.${self:custom.stage}.logLevel}

functions:
  getBudget:
    memorySize: 512
    timeout: 30
    handler: functions/getBudget.handle
    package:
      exclude:
        - ./**
      include:
        - functions/getBudget.py
    events:
      - http:
          path: /{accountId}/{budgetName}
          method: GET
          request:
            parameters:
              paths:
                accountId: true
                budgetName: true
              headers:
                aws_role_name: true
                aws_access_key_id: true
                aws_secret_access_key: true
